### ISSUE TITLE
Runtimewarning divide by zero and DeprecationWarning np.int

### ISSUE THREAD

**Issue by Aquaplant** [bosborne/pyTMHMM#1]
Hello,

I am running Python version 3.7 with pyTMHMM version 1.3.2.
My machine:
> No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

Warning message for each run: 
> anaconda3/envs/promo/lib/python3.7/site-packages/pyTMHMM/api.py:20: **RuntimeWarning**:  divide by zero encountered in log   _, path = viterbi(sequence, *model)

This bugs me as some important calculations might have gone wrong, resulting in erroneous predictions. So far I could not figure out what is going wrong and would appreciate a fix. The warnings all lead to #https://github.com/bosborne/pyTMHMM/blob/0c341ca9550967cc17fc36569a77deb0416e4c77/pyTMHMM/api.py#L20

Sometimes in addition: 
> anaconda3/envs/promo/lib/python3.7/site-packages/pyTMHMM/api.py:20: **DeprecationWarning**: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  _, path = viterbi(sequence, *model)

Minimum working example (also found here: [Testfield.txt](https://github.com/bosborne/pyTMHMM/files/14347670/Testfield.txt))
`import pyTMHMM
from random import choice, randint, seed
from warnings import simplefilter

simplefilter("always")
seed(42)
alphabet = "ACDEFGHIKLMNPQRSTVWY"

for t in range(10):
    sequence = ''.join([choice(alphabet) for i in range(randint(10, 50))])
    print(sequence)
    out = pyTMHMM.predict(sequence)
    # print(out)
`

**Comment by bosborne** [comment]
Fixed the "divide by zero" error, version 1.3.3 uploaded to pypi
